<?php
use Drupal\Core\Entity\EntityTypeInterface;
use Drupal\Core\Field\BaseFieldDefinition;
use Drupal\Core\Field\FieldStorageDefinitionInterface;

/**
 * Ajouter la traduction sur les champs name de model_cv et cv_entity.
 * implement hook_update_8001
 *
 * @see https://www.drupal.org/node/2554097
 */
function ___buildercv_update_8001() {
  /**
   *
   * @var \Drupal\Core\Entity\EntityDefinitionUpdateManagerInterface $updateManager
   */
  $updateManager = \Drupal::entityDefinitionUpdateManager();
  /**
   *
   * @var \Drupal\Core\Field\BaseFieldDefinition $nameModelCv
   */
  $nameModelCv = $updateManager->getFieldStorageDefinition('name', 'model_cv');
  $nameModelCv->setTranslatable(true);
  $nameModelCv->setSetting('max_length', 250);
  $updateManager->updateFieldStorageDefinition($nameModelCv);
  /**
   *
   * @var \Drupal\Core\Field\BaseFieldDefinition $nameCvEntity
   */
  $nameCvEntity = $updateManager->getFieldStorageDefinition('name', 'cv_entity');
  $nameCvEntity->setTranslatable(true);
  $nameCvEntity->setSetting('max_length', 250);
  $updateManager->updateFieldStorageDefinition($nameCvEntity);
}

/**
 * implement hook_entity_base_field_info
 *
 * @param EntityTypeInterface $entity_type
 */
function buildercv_entity_base_field_info(EntityTypeInterface $entity_type) {
  $fields = [];
  if ($entity_type->id() == 'model_cv' || $entity_type->id() == 'cv_entity') {
    if (\Drupal::moduleHandler()->moduleExists('domain')) {
      __buildercv_fields_domain($fields);
    }
  }
  return $fields;
}

/**
 *
 * @param array $fields
 */
function __buildercv_fields_domain(array &$fields) {
  $field_access = \Drupal\domain_access\DomainAccessManagerInterface::DOMAIN_ACCESS_FIELD;
  $field_source = \Drupal\domain_source\DomainSourceElementManagerInterface::DOMAIN_SOURCE_FIELD;
  //
  $fields[$field_access] = BaseFieldDefinition::create('entity_reference')->setLabel(t(" Domain access "))->setCardinality(FieldStorageDefinitionInterface::CARDINALITY_UNLIMITED)->setTranslatable(false)->setDisplayOptions('form', [
    'type' => 'select2_entity_reference',
    'weight' => 40,
    'settings' => [
      'autocomplete' => true
    ]
  ])->setSetting('handler', 'default')->setSetting('target_type', 'domain')->setDisplayConfigurable('form', TRUE)->setDisplayConfigurable('view', TRUE)->setDefaultValueCallback('\Drupal\buildercv\Buildercv::getActiveDomain');
  //
  $fields[$field_source] = BaseFieldDefinition::create('entity_reference')->setLabel(t(" Domain source "))->setDisplayOptions('form', [
    'type' => 'options_select',
    'weight' => 40
  ])->setSetting('handler', 'default')->setSetting('target_type', 'domain')->setDisplayConfigurable('form', TRUE)->setDisplayConfigurable('view', TRUE)->setTranslatable(false);
}

/**
 * Implements hook_theme().
 */
function buildercv_theme() {
  $hooks = [];
  $hooks['buildercv_experience_formatter'] = [
    'preprocess functions' => [
      'template_preprocess_buildercv_experience_formatter'
    ],
    'render element' => 'element',
    'file' => 'buildercv.theme.inc'
  ];
  $hooks['buildercv_value_niveau_formatter'] = [
    'preprocess functions' => [
      'template_preprocess_buildercv_value_niveau_formatter'
    ],
    'render element' => 'element',
    'file' => 'buildercv.theme.inc'
  ];
  $hooks['buildercv_value_niveau_formatter2'] = $hooks['buildercv_value_niveau_formatter'];
  $hooks['buildercv_experience_formatter2'] = $hooks['buildercv_experience_formatter'];
  $hooks['buildercv_experience_formatter3'] = [
    'preprocess functions' => [
      'template_preprocess_buildercv_experience_formatter3'
    ],
    'render element' => 'element',
    'file' => 'buildercv.theme.inc'
  ];
  $hooks['buildercv_experience_formatter4'] = $hooks['buildercv_experience_formatter3'];
  $hooks['buildercv_icon_text'] = [
    'preprocess functions' => [
      'template_preprocess_buildercv_icon_text'
    ],
    'render element' => 'element',
    'file' => 'buildercv.theme.inc'
  ];
  $hooks['buildercv_icon_text_svg'] = $hooks["buildercv_icon_text"];
  $hooks['buildercv_field_chart'] = [
    'preprocess functions' => [
      'template_preprocess_buildercv_field_chart'
    ],
    'render element' => 'element',
    'file' => 'buildercv.theme.inc'
  ];
  $hooks['buildercv_text_bg'] = [
    'preprocess functions' => [
      'template_preprocess_buildercv_text_bg'
    ],
    'render element' => 'element',
    'file' => 'buildercv.theme.inc'
  ];
  return $hooks;
}
