# Schema for the configuration files of the buildercv module.
buildercv.settings:
  type: config_object
  label: 'buildercv settings'
  mapping:
    example:
      type: string
      label: 'Example'
